name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM SÃ£o Paulo time (UTC-3)
    - cron: "0 3 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # REQUIRED: checkout repository so README.md exists
      - uses: actions/checkout@v4

      # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          ### meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: BrenoFariasdaSilva/BrenoFariasdaSilva

          ### content
          SHOW_TITLE: true
          SECTION_NAME: waka
          CODE_LANG: python
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML

          ### commit
          COMMIT_MESSAGE: "Updated WakaTime stats"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Breno Farias da Silva
          AUTHOR_EMAIL: breno.vicio78@gmail.com
